language: node_js
node_js: "7"

before_install: cd frontend
install: npm i

jobs:
  include:
      node_js: "7"
    - stage: "frontend"
      name: "Building"
      script: npm start
    - name: "Testing"
      script: npm test